import Head from "next/head";

import { searchProducts } from "@/utils/search";
import { getProducts } from "@/services/products";
import HomePage from "@/components/templates/HomePage";

export default function Home(props) {
  
  return (
    <>
      <Head>
        <title>فروشگاه</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/assets/images/logo.svg" />
      </Head>
      <HomePage {...props} />
    </>
  );
}

export const getServerSideProps = async (context) => {
  const { query } = context;
  const price = { min: query.min, max: query.max };

  try {
    const data = await getProducts(query.page, price);
    const allProducts = data.data.data;
    const products = searchProducts(allProducts, query.search);
    return {
      props: { products, isData: data.data },
    };
  } catch (error) {
    return {
      props: { error: { status: error.status } },
    };
  }
};
