import Head from "next/head";

import { getProduct } from "@/services/products";
import ProductDetailsPage from "@/components/templates/ProductDetailsPage";

function ProductDetail({ product }) {
  return (
    <>
      <Head>
        <title>{product.name}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/assets/images/logo.svg" />
      </Head>
      <ProductDetailsPage {...product} />;
    </>
  );
}

export default ProductDetail;

export async function getServerSideProps(context) {
  const {
    params: { productId },
  } = context;
  try {
    const data = await getProduct(productId);
    return {
      props: { product: data.data },
    };
  } catch (error) {
    return {
      props: { error: { status: error.status } },
    };
  }
}
