import Head from "next/head";

import RegistrationForm from "@/components/templates/RegistrationForm";

function Signup() {
  return (
    <>
      <Head>
        <title>ثبت نام</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/assets/images/logo.svg" />
      </Head>
      <RegistrationForm />;
    </>
  );
}

export default Signup;
